---
locale: es
tags: []
layout: input_bottom
editor: 0
type: interactive
extra_visible: false
teacher_info: ''
manual_evaluation: false
choices: []
goal: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  kind: last_query_outputs
  output: |-
    a
    d
    i
    v
    i
    n
    a
    d
    o
    r
    undefined
name: De visita
